//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicShuffler {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MusicShuffler.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string AddButton {
            get {
                return ResourceManager.GetString("AddButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add From Library.
        /// </summary>
        internal static string AddFromLibraryButton {
            get {
                return ResourceManager.GetString("AddFromLibraryButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add songs from {0}.
        /// </summary>
        internal static string AddSongsFromArtist {
            get {
                return ResourceManager.GetString("AddSongsFromArtist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add songs from genre {0}.
        /// </summary>
        internal static string AddSongsFromGenre {
            get {
                return ResourceManager.GetString("AddSongsFromGenre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Songs From Library.
        /// </summary>
        internal static string AddSongsFromLibrary {
            get {
                return ResourceManager.GetString("AddSongsFromLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string AF_MboxCaption_Warning {
            get {
                return ResourceManager.GetString("AF_MboxCaption_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you add the song &quot;{0}&quot; to the list, there will be less than 20 % available for randomly selected songs. Do you want to proceed?.
        /// </summary>
        internal static string AF_MboxText_LessThan20 {
            get {
                return ResourceManager.GetString("AF_MboxText_LessThan20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By adding song &quot;{0}&quot; to the playlist you will exceed the specified target size. The playlist might not fit the given destination. Are you sure you want to proceed?.
        /// </summary>
        internal static string AF_MboxText_OverTargetSize {
            get {
                return ResourceManager.GetString("AF_MboxText_OverTargetSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        internal static string ApplyButton {
            get {
                return ResourceManager.GetString("ApplyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string CopyButton {
            get {
                return ResourceManager.GetString("CopyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to copy the file {0} to the destination. The error message was:\r\n\r\n{1}.
        /// </summary>
        internal static string CopyFailed {
            get {
                return ResourceManager.GetString("CopyFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying songs....
        /// </summary>
        internal static string CopyingSongs {
            get {
                return ResourceManager.GetString("CopyingSongs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying file {0} of {1}.
        /// </summary>
        internal static string CurrentFileIndicator {
            get {
                return ResourceManager.GetString("CurrentFileIndicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done  {0} %.
        /// </summary>
        internal static string DonePercentage {
            get {
                return ResourceManager.GetString("DonePercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit filters.
        /// </summary>
        internal static string EditFilters {
            get {
                return ResourceManager.GetString("EditFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Filters.
        /// </summary>
        internal static string EditFiltersButton {
            get {
                return ResourceManager.GetString("EditFiltersButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclude artist {0}.
        /// </summary>
        internal static string ExcludeArtist {
            get {
                return ResourceManager.GetString("ExcludeArtist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclude genre {0}.
        /// </summary>
        internal static string ExcludeGenre {
            get {
                return ResourceManager.GetString("ExcludeGenre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclude selected artists:.
        /// </summary>
        internal static string ExcludeSelectedArtists {
            get {
                return ResourceManager.GetString("ExcludeSelectedArtists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclude selected genres:.
        /// </summary>
        internal static string ExcludeSelectedGenres {
            get {
                return ResourceManager.GetString("ExcludeSelectedGenres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extracting song metadata... Please wait.
        /// </summary>
        internal static string ExtractingMetadata {
            get {
                return ResourceManager.GetString("ExtractingMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished.
        /// </summary>
        internal static string Finished {
            get {
                return ResourceManager.GetString("Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hours.
        /// </summary>
        internal static string Hours {
            get {
                return ResourceManager.GetString("Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit songs maximum duration to:.
        /// </summary>
        internal static string LimitMaximumDuration {
            get {
                return ResourceManager.GetString("LimitMaximumDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit songs minimum duration to:.
        /// </summary>
        internal static string LimitMinimumDuration {
            get {
                return ResourceManager.GetString("LimitMinimumDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading library....
        /// </summary>
        internal static string LoadingLibrary {
            get {
                return ResourceManager.GetString("LoadingLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string MboxCaption_Error {
            get {
                return ResourceManager.GetString("MboxCaption_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        internal static string MF_BrowseButton {
            get {
                return ResourceManager.GetString("MF_BrowseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination directory:.
        /// </summary>
        internal static string MF_DestinationDirectoryLabel {
            get {
                return ResourceManager.GetString("MF_DestinationDirectoryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Playlist.
        /// </summary>
        internal static string MF_GeneratePlaylistButton {
            get {
                return ResourceManager.GetString("MF_GeneratePlaylistButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MB.
        /// </summary>
        internal static string MF_MbLabel {
            get {
                return ResourceManager.GetString("MF_MbLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory not found.
        /// </summary>
        internal static string MF_MboxCaption_DirectoryNotFound {
            get {
                return ResourceManager.GetString("MF_MboxCaption_DirectoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required value not set.
        /// </summary>
        internal static string MF_MboxCaption_RequiredValue {
            get {
                return ResourceManager.GetString("MF_MboxCaption_RequiredValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target size is less than 50 MB.
        /// </summary>
        internal static string MF_MboxCaption_TargetSizeLessThan50 {
            get {
                return ResourceManager.GetString("MF_MboxCaption_TargetSizeLessThan50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough disk space.
        /// </summary>
        internal static string MF_MboxCaption_TargetSizeOverSpaceLeft {
            get {
                return ResourceManager.GetString("MF_MboxCaption_TargetSizeOverSpaceLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select at least one search directory..
        /// </summary>
        internal static string MF_MboxText_AtLeastOneSearchDirectory {
            get {
                return ResourceManager.GetString("MF_MboxText_AtLeastOneSearchDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given destination directory does not exist. Would you like to create it now?.
        /// </summary>
        internal static string MF_MboxText_DestinationDirectoryNotFound {
            get {
                return ResourceManager.GetString("MF_MboxText_DestinationDirectoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must set the destination directory.
        /// </summary>
        internal static string MF_MboxText_DestinationDirectoryRequired {
            get {
                return ResourceManager.GetString("MF_MboxText_DestinationDirectoryRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create directory {0}. The error message was:\r\n\r\n{1}.
        /// </summary>
        internal static string MF_MboxText_DirectoryCreateFailed {
            get {
                return ResourceManager.GetString("MF_MboxText_DirectoryCreateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following search directory does not exist, and it won&apos;t be searched for audio files:\r\n\r\n{0}.
        /// </summary>
        internal static string MF_MboxText_SearchDirectoryNotFound {
            get {
                return ResourceManager.GetString("MF_MboxText_SearchDirectoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified target size is less than 50 MB. Would you like to reconsider the amount?.
        /// </summary>
        internal static string MF_MboxText_TargetSizeLessThan50 {
            get {
                return ResourceManager.GetString("MF_MboxText_TargetSizeLessThan50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified target size {0} is more than the available free space on the selected disk. There&apos;s only {1} of free space available..
        /// </summary>
        internal static string MF_MboxText_TargetSizeOverSpaceLeft {
            get {
                return ResourceManager.GetString("MF_MboxText_TargetSizeOverSpaceLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string MF_RemoveDirectoryButton {
            get {
                return ResourceManager.GetString("MF_RemoveDirectoryButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directories to search:.
        /// </summary>
        internal static string MF_SearchDirectoriesLabel {
            get {
                return ResourceManager.GetString("MF_SearchDirectoriesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target size:.
        /// </summary>
        internal static string MF_TargetSizeLabel {
            get {
                return ResourceManager.GetString("MF_TargetSizeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutes.
        /// </summary>
        internal static string Minutes {
            get {
                return ResourceManager.GetString("Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlist.
        /// </summary>
        internal static string Playlist {
            get {
                return ResourceManager.GetString("Playlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress.
        /// </summary>
        internal static string Progress {
            get {
                return ResourceManager.GetString("Progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove song from playlist.
        /// </summary>
        internal static string RemoveSong {
            get {
                return ResourceManager.GetString("RemoveSong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reshuffle.
        /// </summary>
        internal static string ReshuffleButton {
            get {
                return ResourceManager.GetString("ReshuffleButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reshuffle Selected.
        /// </summary>
        internal static string ReshuffleSelectedButton {
            get {
                return ResourceManager.GetString("ReshuffleSelectedButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seconds.
        /// </summary>
        internal static string Seconds {
            get {
                return ResourceManager.GetString("Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select all.
        /// </summary>
        internal static string SelectAllButton {
            get {
                return ResourceManager.GetString("SelectAllButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album.
        /// </summary>
        internal static string SongList_Album {
            get {
                return ResourceManager.GetString("SongList_Album", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artist.
        /// </summary>
        internal static string SongList_Artist {
            get {
                return ResourceManager.GetString("SongList_Artist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        internal static string SongList_Duration {
            get {
                return ResourceManager.GetString("SongList_Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Path.
        /// </summary>
        internal static string SongList_FilePath {
            get {
                return ResourceManager.GetString("SongList_FilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Size.
        /// </summary>
        internal static string SongList_FileSize {
            get {
                return ResourceManager.GetString("SongList_FileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genre.
        /// </summary>
        internal static string SongList_Genre {
            get {
                return ResourceManager.GetString("SongList_Genre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlist.
        /// </summary>
        internal static string SongList_Playlist {
            get {
                return ResourceManager.GetString("SongList_Playlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string SongList_Title {
            get {
                return ResourceManager.GetString("SongList_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The songs are being copied. Please wait..
        /// </summary>
        internal static string SongsBeingCopied {
            get {
                return ResourceManager.GetString("SongsBeingCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Songs You Added.
        /// </summary>
        internal static string SongsYouAdded {
            get {
                return ResourceManager.GetString("SongsYouAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total File Size:.
        /// </summary>
        internal static string TotalFileSize {
            get {
                return ResourceManager.GetString("TotalFileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uncheck all.
        /// </summary>
        internal static string UncheckAll {
            get {
                return ResourceManager.GetString("UncheckAll", resourceCulture);
            }
        }
    }
}
